#!/bin/bash

set -eux

# This script trims down the base Ubuntu 22.04 rootfs.
# It removes unnecessary (for our purposes) packages like
# thunderbird, libreoffice, rhythmbox, aisleriot etc.

apt update

apt remove -y --purge \
	aisleriot \
	alsa-utils \
	branding-ubuntu \
	brltty \
	btrfs-progs \
	duplicity \
	fonts-arphic-ukai \
	fonts-arphic-uming \
	fonts-beng \
	fonts-beng-extra \
	fonts-deva \
	fonts-deva-extra \
	fonts-gargi \
	fonts-gubbi \
	fonts-gujr \
	fonts-gujr-extra \
	fonts-guru \
	fonts-guru-extra \
	fonts-indic \
	fonts-kacst \
	fonts-kacst-one \
	fonts-kalapi \
	fonts-khmeros-core \
	fonts-knda \
	fonts-lao \
	fonts-lklug-sinhala \
	fonts-lohit-beng-assamese \
	fonts-lohit-beng-bengali \
	fonts-lohit-deva \
	fonts-lohit-gujr \
	fonts-lohit-guru \
	fonts-lohit-knda \
	fonts-lohit-mlym \
	fonts-lohit-orya \
	fonts-lohit-taml \
	fonts-lohit-taml-classical \
	fonts-lohit-telu \
	fonts-mlym \
	fonts-nakula \
	fonts-navilu \
	fonts-noto-cjk \
	fonts-noto-color-emoji \
	fonts-orya \
	fonts-orya-extra \
	fonts-pagul \
	fonts-sahadeva \
	fonts-samyak-deva \
	fonts-samyak-gujr \
	fonts-samyak-mlym \
	fonts-samyak-taml \
	fonts-sarai \
	fonts-sil-abyssinica \
	fonts-sil-padauk \
	fonts-smc \
	fonts-smc-anjalioldlipi \
	fonts-smc-chilanka \
	fonts-smc-dyuthi \
	fonts-smc-gayathri \
	fonts-smc-karumbi \
	fonts-smc-keraleeyam \
	fonts-smc-manjari \
	fonts-smc-meera \
	fonts-smc-rachana \
	fonts-smc-raghumalayalamsans \
	fonts-smc-suruma \
	fonts-smc-uroob \
	fonts-taml \
	fonts-telu \
	fonts-telu-extra \
	fonts-teluguvijayam \
	fonts-thai-tlwg \
	fonts-tibetan-machine \
	fonts-tlwg-garuda \
	fonts-tlwg-garuda-ttf \
	fonts-tlwg-kinnari \
	fonts-tlwg-kinnari-ttf \
	fonts-tlwg-laksaman \
	fonts-tlwg-laksaman-ttf \
	fonts-tlwg-loma \
	fonts-tlwg-loma-ttf \
	fonts-tlwg-mono \
	fonts-tlwg-mono-ttf \
	fonts-tlwg-norasi \
	fonts-tlwg-norasi-ttf \
	fonts-tlwg-purisa \
	fonts-tlwg-purisa-ttf \
	fonts-tlwg-sawasdee \
	fonts-tlwg-sawasdee-ttf \
	fonts-tlwg-typewriter \
	fonts-tlwg-typewriter-ttf \
	fonts-tlwg-typist \
	fonts-tlwg-typist-ttf \
	fonts-tlwg-typo \
	fonts-tlwg-typo-ttf \
	fonts-tlwg-umpush \
	fonts-tlwg-umpush-ttf \
	fonts-tlwg-waree \
	fonts-tlwg-waree-ttf \
	fonts-ubuntu \
	fonts-urw-base35 \
	fonts-yrsa-rasa \
	genisoimage \
	gnome-bluetooth \
	gnome-bluetooth-3-common \
	gnome-bluetooth-common \
	gnome-mahjongg \
	gnome-mines \
	gnome-sudoku \
	gnome-user-docs-de \
	gnome-user-docs-es \
	gnome-user-docs-fr \
	gnome-user-docs-it \
	gnome-user-docs-pt \
	gnome-user-docs-ru \
	gnome-user-docs-zh-hans \
	humanity-icon-theme \
	hunspell-de-at-frami \
	hunspell-de-ch-frami \
	hunspell-de-de-frami \
	hunspell-en-au \
	hunspell-en-ca \
	hunspell-en-gb \
	hunspell-en-us \
	hunspell-en-za \
	hunspell-es \
	hunspell-fr \
	hunspell-fr-classical \
	hunspell-it \
	hunspell-pt-br \
	hunspell-pt-pt \
	hunspell-ru \
	hyphen-de \
	hyphen-en-ca \
	hyphen-es \
	hyphen-fr \
	hyphen-it \
	hyphen-pt-br \
	hyphen-pt-pt \
	hyphen-ru \
	ibus-chewing \
	ibus-hangul \
	ibus-libpinyin \
	ibus-m17n \
	ibus-mozc \
	ibus-table \
	ibus-table-cangjie \
	ibus-table-cangjie-big \
	ibus-table-cangjie3 \
	ibus-table-cangjie5 \
	ibus-table-quick-classic \
	ibus-table-wubi \
	ibus-unikey \
	language-pack-de \
	language-pack-de-base \
	language-pack-es \
	language-pack-es-base \
	language-pack-fr \
	language-pack-fr-base \
	language-pack-gnome-de \
	language-pack-gnome-de-base \
	language-pack-gnome-es \
	language-pack-gnome-es-base \
	language-pack-gnome-fr \
	language-pack-gnome-fr-base \
	language-pack-gnome-it \
	language-pack-gnome-it-base \
	language-pack-gnome-pt \
	language-pack-gnome-pt-base \
	language-pack-gnome-ru \
	language-pack-gnome-ru-base \
	language-pack-gnome-zh-hans \
	language-pack-gnome-zh-hans-base \
	language-pack-it \
	language-pack-it-base \
	language-pack-pt \
	language-pack-pt-base \
	language-pack-ru \
	language-pack-ru-base \
	language-pack-zh-hans \
	language-pack-zh-hans-base \
	'libreoffice*' \
	mozc-server \
	'mythes-*' \
	orca \
	poppler-data \
	ppp \
	remmina-common \
	'rhythmbox*' \
	rygel \
	seahorse \
	sgml-data \
	shotwell \
	simple-scan \
	speech-dispatcher \
	tcpdump \
	thin-provisioning-tools \
	'thunderbird*' \
	totem-common \
	tracker-extract \
	transmission-gtk \
	ubiquity \
	ubiquity-slideshow-ubuntu \
	ubuntu-advantage-tools \
	ubuntu-docs \
	ubuntu-mono \
	ubuntu-wallpapers-jammy \
	wbrazilian \
	wfrench \
	witalian \
	wngerman \
	wogerman \
	wportuguese \
	wswiss \
	xcursor-themes \
	xdg-desktop-portal \
	xfonts-base \
	xfsprogs \
	yelp \
	yelp-xsl \
	zenity-common \
	zsys

# remove unused packages
apt autoremove -y
